workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: NexlinxEMS-Clean-Mobile-App
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Build Android APK
        script: |
          npx expo prebuild --platform android --clean
          cd android && ./gradlew assembleRelease
    artifacts:
      - NexlinxEMS-Clean-Mobile-App/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - naeemhaq1@gmail.com
        notify:
          success: true
          failure: true